name: Python Artifact Demo

on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Create-Artifact:
    runs-on: self-hosted
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Python 3.11
        run: |
          python3.11 --version
          python3.11 -m pip --version

      - name: Install Project Dependencies
        run: |
          python3.11 -m pip install --upgrade pip


      - name: check python version
        run: python --version

      - name: Run Python Program
        run: python app.py

      - name: Show genaretd file
        run: cat result.txt

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-result-file
          path: result.txt
